#!/usr/bin/with-contenv bash

# strip leading slash if present in set variable
[[ "$CONTEXT_PATH" ]] && CONTEXT_PATH="${CONTEXT_PATH#/}"

# set url base to / if variable not set, readding leading slash if variable is set.
URL_BASE="/${CONTEXT_PATH}"


cd /app/booksonic || exit

exec \
	s6-setuidgid abc java \
	-D"${BOOKSONIC_OPT_PREFIX}".home=/config \
	-D"${BOOKSONIC_OPT_PREFIX}".defaultPodcastFolder=/podcasts \
	-D"${BOOKSONIC_OPT_PREFIX}".defaultMusicFolder=/books \
	-jar /usr/share/java/jetty-runner.jar \
	--host 0.0.0.0 --port 4040 --path "${URL_BASE}" \
	booksonic.war
